apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SERVER_PORT: "8080"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ifmvp-auth-postgresql:5432/statsdb
