apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_COMMAND_URL: jdbc:postgresql://email-service:5432/emaildb
  SPRING_DATASOURCE_QUERY_URL: jdbc:postgresql://email-service:5432/emailviews
