apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_COMMAND_JDBC-URL: jdbc:postgresql://postgres-ifmvp-email-postgresql:5432/emaildb
  SPRING_DATASOURCE_QUERY_JDBC-URL: jdbc:postgresql://postgres-ifmvp-email-postgresql:5432/emailviews
