server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

spring:
  application:
    name: mock-service
  # mock/src/main/resources/application.yml에 추가
    # H2 인메모리 데이터베이스 설정 추가
datasource:
  url: jdbc:h2:mem:mockdb;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.Driver
  username: sa
  password:

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=ifmvp;AccountKey=0hBdcnBFzZwXRPjGeF8C8U/cbh4X4uK06IWCUHtTeTy4q64t8LlpXi9D8Xcxp5enTpm6aVg8XCau+AStexwJww==;EndpointSuffix=core.windows.net}
    container:
      attachments: ${AZURE_CONTAINER_ATTACHMENTS:email-attachments}
  servicebus:
    connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING:Endpoint=sb://sb-if-ifmvp.servicebus.windows.net/;SharedAccessKeyName=if-backend;SharedAccessKey=IicFGjdVwp8YlkSCKYgRyOZ7cubKSvHJG+ASbH5ah9M=}
    queue:
      email-events: ${AZURE_QUEUE_EMAIL_EVENTS:email-events}
      email-open-events: ${AZURE_QUEUE_EMAIL_EVENTS:email-open-events}
      attachment-click-events: ${AZURE_QUEUE_OPEN_EVENTS:email-open-events}

jwt:
  secret-key: ${JWT_SECRET_KEY:defaultSecretKey}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

logging:
  level:
    root: INFO
    com.email.mock: DEBUG
    com.azure: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    tags:
      app: ${spring.application.name}
      instance: ${HOSTNAME:localhost}:${server.port}
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1000ms, 2000ms
